### ISSUE TITLE
Using the Input x Output x pins from a Selector Component doesn't switch correctly.

### ISSUE THREAD

**Issue by jcerecke** [q-sys-community/q-sys-plugin-lightware-matrix#1]
Using a selector wired to the "input x output x" pins produces incorrect switching behaviour. This is because the EventHandler for these pins does not check if the Boolean is True before executing the switch. The Selector component produces a Boolean True on the newly selected input, and a second Boolean False on the previously selected input which then causes the EventHandler in the plugin to be triggered twice.

![image](https://user-images.githubusercontent.com/43508126/219988830-f5cc98f2-231e-42a6-85ee-80cd3d998106.png)

Suggest the following at Line 636:
```
Controls["input_" .. p .. "-output_" .. i].EventHandler = function()
  if Controls["input_" .. p .. "-output_" .. i].Boolean then
    Controls["output_" .. i].String = tostring(p)
    tie_command(Controls["output_" .. i].String, i)
  end
end
```

**Comment by UsernameDan** [comment]
Thanks, fixed in latest version.
